apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/fluentd-containers.pos
      tag kubernetes.*
      <parse>
        @type json
        unmatched_lines true
      </parse>
    </source>

    <match kubernetes.**>
      @type stdout
    </match>
