apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
spec:
  selector:
    app: node-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
chaima@LAPTOP-7175BV7U:~$ cat fluentd-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/fluentd-containers.pos
      tag kubernetes.*
      <parse>
        @type json
        unmatched_lines
      </parse>
    </source>

    <match kubernetes.**>
      @type stdout
    </match>
