apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd
spec:
  selector:
    matchLabels:
      k8s-app: fluentd
  template:
    metadata:
      labels:
        k8s-app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.14-1
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: fluentd-pos
          mountPath: /fluentd/log
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: fluentd-pos
        emptyDir: {}
